const tabs = document.querySelectorAll('.game-tab');
const panels = { reaction: document.getElementById('reactionGame'), memory: document.getElementById('memoryGame'), clicker: document.getElementById('clickerGame'), color: document.getElementById('colorGame'), odd: document.getElementById('oddGame') };
const cheats = { reaction: false, memory: false, clicker: false, color: false, odd: false };
tabs.forEach(tab => tab.addEventListener('click', () => { tabs.forEach(item => item.classList.remove('active')); tab.classList.add('active'); Object.values(panels).forEach(panel => panel.classList.add('hidden')); panels[tab.dataset.game].classList.remove('hidden'); }));

let reactionState = 'idle', reactionTimer, reactionStart, reactionBestValue = Infinity;
const reactionBoard = document.getElementById('reactionBoard');
reactionBoard.addEventListener('click', () => {
  if (cheats.reaction) { reactionState = 'idle'; reactionBoard.className = 'reaction-board ready'; reactionBoard.innerHTML = '0 ms<br><small>owner speed enabled</small>'; document.getElementById('reactionTime').textContent = '0 ms'; return; }
  if (reactionState === 'ready') { const time = Math.round(performance.now() - reactionStart); reactionState = 'idle'; reactionBoard.className = 'reaction-board'; reactionBoard.innerHTML = `${time} ms<br><small>click to try again</small>`; document.getElementById('reactionTime').textContent = `${time} ms`; if (time < reactionBestValue) { reactionBestValue = time; document.getElementById('reactionBest').textContent = `${time} ms`; } return; }
  if (reactionState === 'waiting') { clearTimeout(reactionTimer); reactionState = 'idle'; reactionBoard.className = 'reaction-board too-soon'; reactionBoard.innerHTML = `Too soon!<br><small>click to reset</small>`; return; }
  reactionState = 'waiting'; reactionBoard.className = 'reaction-board'; reactionBoard.innerHTML = 'Wait for it...'; reactionTimer = setTimeout(() => { reactionState = 'ready'; reactionStart = performance.now(); reactionBoard.className = 'reaction-board ready'; reactionBoard.innerHTML = 'CLICK!'; }, 1200 + Math.random() * 2600);
});

const symbols = ['●','◆','▲','★','♥','☀']; let memoryCards = [], firstCard, lockBoard = false, moves = 0, pairs = 0;
function setupMemory() { const board = document.getElementById('memoryBoard'); memoryCards = [...symbols, ...symbols].sort(() => Math.random() - .5); board.innerHTML = ''; firstCard = null; lockBoard = false; moves = 0; pairs = 0; document.getElementById('memoryMoves').textContent = '0'; document.getElementById('memoryPairs').textContent = '0 / 6'; memoryCards.forEach((symbol, index) => { const card = document.createElement('button'); card.className = 'memory-card'; card.dataset.symbol = symbol; card.dataset.index = index; card.textContent = symbol; card.addEventListener('click', flipCard); board.appendChild(card); }); }
function flipCard(event) { const card = event.currentTarget; if (lockBoard || card === firstCard || card.classList.contains('matched')) return; card.classList.add('flipped'); if (!firstCard) { firstCard = card; return; } moves++; document.getElementById('memoryMoves').textContent = moves; if (firstCard.dataset.symbol === card.dataset.symbol) { firstCard.classList.add('matched'); card.classList.add('matched'); firstCard = null; pairs++; document.getElementById('memoryPairs').textContent = `${pairs} / 6`; } else { lockBoard = true; setTimeout(() => { firstCard.classList.remove('flipped'); card.classList.remove('flipped'); firstCard = null; lockBoard = false; }, 650); } }
document.getElementById('memoryReset').addEventListener('click', setupMemory); setupMemory();

let clickActive = false, clickScore = 0, clickTimer, clickEnd;
const clickBoard = document.getElementById('clickBoard'), target = document.getElementById('target'), clickStart = document.getElementById('clickStart');
function moveTarget() { const maxX = clickBoard.clientWidth - 70, maxY = clickBoard.clientHeight - 70; target.style.left = `${12 + Math.random() * Math.max(0, maxX - 12)}px`; target.style.top = `${12 + Math.random() * Math.max(0, maxY - 12)}px`; }
function startClicker() { clickActive = true; clickScore = 0; clickEnd = performance.now() + 20000; target.style.display = 'block'; clickStart.style.display = 'none'; moveTarget(); clickTimer = setInterval(() => { const left = Math.max(0, clickEnd - performance.now()); if (cheats.clicker) { document.getElementById('clickTime').textContent = '∞'; return; } document.getElementById('clickTime').textContent = `${(left / 1000).toFixed(1)}s`; if (!left) { clearInterval(clickTimer); clickActive = false; target.style.display = 'none'; clickStart.style.display = 'grid'; clickStart.innerHTML = `${clickScore} hits!<br><small>click to play again</small>`; } }, 50); }
clickStart.addEventListener('click', startClicker); target.addEventListener('click', () => { if (!clickActive) return; clickScore++; document.getElementById('clickScore').textContent = clickScore; moveTarget(); });
const colorNames = ['coral', 'sunshine', 'mint', 'sky'];
const colorValues = { coral: '#ff6b54', sunshine: '#ffd166', mint: '#73bb91', sky: '#5d9cdb' };
let colorAnswer = '', colorScore = 0, colorRound = 0;
function setupColor() { colorRound++; document.getElementById('colorRound').textContent = colorRound; colorAnswer = colorNames[Math.floor(Math.random() * colorNames.length)]; document.getElementById('colorPrompt').textContent = colorAnswer; const options = [...colorNames].sort(() => Math.random() - .5); const container = document.getElementById('colorOptions'); container.innerHTML = ''; options.forEach(name => { const button = document.createElement('button'); button.className = 'color-option'; button.textContent = name; button.style.background = colorValues[name]; button.addEventListener('click', () => { if (name === colorAnswer) { colorScore++; document.getElementById('colorScore').textContent = colorScore; const best = Math.max(colorScore, Number(localStorage.getItem('colorBest') || 0)); localStorage.setItem('colorBest', best); document.getElementById('colorBest').textContent = best; setupColor(); } else { colorScore = 0; document.getElementById('colorScore').textContent = '0'; setupColor(); } }); container.appendChild(button); }); if (cheats.color) highlightColor(); }
function highlightColor() { document.querySelectorAll('.color-option').forEach(button => button.classList.toggle('cheat', button.textContent === colorAnswer)); }
setupColor(); document.getElementById('colorBest').textContent = localStorage.getItem('colorBest') || '0';

const oddBoard = document.getElementById('oddBoard'); let oddIndex = 0, oddRound = 0, oddBest = Number(localStorage.getItem('oddBest') || 0);
function setupOdd() { oddRound++; document.getElementById('oddRound').textContent = oddRound; const total = Math.min(25, 10 + oddRound * 2); oddIndex = Math.floor(Math.random() * total); oddBoard.innerHTML = ''; for (let index = 0; index < total; index++) { const tile = document.createElement('button'); tile.className = 'odd-tile'; tile.style.filter = index === oddIndex ? 'brightness(0.86)' : 'none'; tile.addEventListener('click', () => { if (index === oddIndex) { oddBest = Math.max(oddBest, oddRound); localStorage.setItem('oddBest', oddBest); document.getElementById('oddBest').textContent = oddBest; setupOdd(); } else { oddRound = 0; setupOdd(); } }); oddBoard.appendChild(tile); } if (cheats.odd) highlightOdd(); }
function highlightOdd() { [...oddBoard.children].forEach((tile, index) => tile.classList.toggle('cheat', index === oddIndex)); }
document.getElementById('oddBest').textContent = oddBest; setupOdd();

const ownerBackdrop = document.getElementById('ownerBackdrop'), ownerPassword = document.getElementById('ownerPassword');
document.getElementById('ownerOpen').addEventListener('click', () => { ownerBackdrop.classList.remove('hidden'); ownerPassword.focus(); });
document.getElementById('ownerClose').addEventListener('click', () => ownerBackdrop.classList.add('hidden'));
document.getElementById('unlockOwner').addEventListener('click', unlockOwner);
ownerPassword.addEventListener('keydown', event => { if (event.key === 'Enter') unlockOwner(); });
function unlockOwner() { if (ownerPassword.value === 'pixelboss') { document.getElementById('passwordView').classList.add('hidden'); document.getElementById('cheatView').classList.remove('hidden'); document.getElementById('passwordError').textContent = ''; } else document.getElementById('passwordError').textContent = 'That password did not work.'; }
document.getElementById('lockOwner').addEventListener('click', () => { document.getElementById('cheatView').classList.add('hidden'); document.getElementById('passwordView').classList.remove('hidden'); ownerPassword.value = ''; });
document.querySelectorAll('[data-cheat]').forEach(input => input.addEventListener('change', event => { const game = event.target.dataset.cheat; cheats[game] = event.target.checked; if (game === 'memory' && event.target.checked) document.querySelectorAll('.memory-card').forEach(card => card.classList.add('flipped')); if (game === 'color' && event.target.checked) highlightColor(); if (game === 'odd' && event.target.checked) highlightOdd(); if (game === 'clicker' && event.target.checked) target.style.width = target.style.height = '95px'; if (game === 'clicker' && !event.target.checked) target.style.width = target.style.height = '59px'; }));
document.getElementById('bestStreak').textContent = localStorage.getItem('pixelBest') || '0';